version: "3"
services:
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - "5672:5672"
      - "8080:15672"
    volumes:
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./rabbitmq/definitions.json:/etc/rabbitmq/definitions.json
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"
    volumes:
      - ./database/tables.sql:/docker-entrypoint-initdb.d/tables.sql
      - ./database/views.sql:/docker-entrypoint-initdb.d/views.sql
      - ./database/triggers.sql:/docker-entrypoint-initdb.d/triggers.sql
