# This workflow will trigger pytest on pull requests

name: Bump version of staging build

# Controls when the workflow will run
on:
  # Triggers the workflow on push events
  push:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "install-test"
  bump-version:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'Bump version from')"

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
          token: ${{ secrets.PAT }}
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
      - name: Install dependencies
        run: make environment
      - name: Configure git
        run: |
          git config --global user.name 'Erik Wahlberger'
          git config --global user.email 'Erik142@users.noreply.github.com'
      - name: Bump version
        run: make devversion
      - name: Push to GitHub
        run: git push
      - name: Push tags to GitHub
        run: git push --tags